config/config/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from vehiculo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.index, name='index'),
    path('vehiculo/', include('vehiculo.urls')),
    path('listar/', views.listar, name='listar'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
]

config/vehiculo/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('add/', views.vehiculo_form, name='vehiculo_form'),
]

config/vehiculo/models.py
from django.db import models

# Create your models here.

class Vehiculo(models.Model):
    MARCA_CHOICES = (
        ('Fiat', 'Fiat'),
        ('Chevrolet', 'Chevrolet'),
        ('Ford', 'Ford'),
        ('Toyota', 'Toyota'),
    )
    
    CATEGORIA_CHOICES = (
        ('Particular','Particular'),
        ('Transporte', 'Transporte'),
        ('Carga', 'Carga')
    )
    
    marca = models.CharField(max_length=20, choices=MARCA_CHOICES, default='Ford')
    modelo = models.CharField(max_length=100)
    serial_carroceria = models.CharField(max_length=50)
    serial_motor = models.CharField(max_length=50)
    categoria = models.CharField(max_length=20, choices=CATEGORIA_CHOICES, default='Particular')
    precio = models.IntegerField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)
    
    class Meta:
        permissions = [("visualizar_catalogo", "visualizar_catalogo")]
    
    def __str__(self) -> str:
        return f'{self.marca} - {self.modelo}'

config/vehiculo/forms.py
from django import forms 
from .models import Vehiculo

class VehiculoForm(forms.ModelForm):
    class Meta:
        model = Vehiculo
        fields= '__all__'

config/vehiculo/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.views import LoginView
from .forms import VehiculoForm
from vehiculo.models import Vehiculo

# Create your views here.

def index(request):
    return render(request, 'index.html')

@login_required(login_url='/')
def listar(request):
    vehiculos = Vehiculo.objects.all()
    
    for vehiculo in vehiculos:
        if vehiculo.precio <= 10000:
            vehiculo.condicion_precio = 'Bajo'
        elif vehiculo.precio > 10000 and vehiculo.precio <= 30000:
            vehiculo.condicion_precio = 'Medio'
        else:
            vehiculo.condicion_precio = 'Alto'
            
    contexto = {'vehiculos': vehiculos}
    
    return render(request, 'listar.html', contexto)

@login_required(login_url='/')
def vehiculo_form(request):
    if request.method == "POST":
        form = VehiculoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('vehiculo_form')
    
    else:
        form = VehiculoForm()
    
    return render(request, 'add.html', {'form': form})

class CustomLoginView(LoginView):
    template_name = 'login.html'
    
    def get_success_url(self) -> str:
        return '/'

config/vehiculo/templates/add.html
{% extends "base.html" %}

{% block content %}

    <div class="container d-flex justify-content-center align-items-center flex-column">
        <h1 class="pt-4 pb-3">Formulario de Ingreso de Vehículos</h1>
        <div class="card col-4">
            <form class="py-4 px-4" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="text-center mt-3">
                    <button class="btn btn-primary" type="submit">Enviar</button>
                </div>
            </form>
        </div>
    </div>
    
{% endblock %}



config/vehiculo/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Catálogo de Vehículos</title>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Vehículos</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" aria-current="page" href="/">Inicio</a>
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="/vehiculo/add/">Agregar</a>
                        <a class="nav-link" href="/listar/">Listar</a>
                    {% endif %}
                </div>
            </div>
            <div class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item my-auto">
                        <span class="navbar-text">
                            Hola, {{ user.username }}
                        </span>
                    </li>
                    <li class="nav-item mx-2">
                        <button type="button" class="btn btn-outline-secondary btn-sm">
                            <a class="nav-link" href="{% url 'logout' %}">Salir</a>
                        </button>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <button type="button" class="btn btn-outline-secondary btn-sm">
                            <a class="nav-link" href="{% url 'login' %}">Iniciar sesión</a>
                        </button>
                    </li>
                {% endif %}
            </div>
        </div>
    </nav>
    
    {% block title %} {% endblock %}

    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

</body>

</html>


config/vehiculo/templates/index.html
{% extends "base.html" %}

{% block title %}
    <h1 class="text-center mt-4">Catálogo de Vehículos</h1>
    <img src="https://png2.cleanpng.com/sh/4757cc40f1b9d22af3d0f1ea8a677c23/L0KzQYm3U8AzN6RBj5H0aYP2gLBuTfNiel53fdD9YXywgrn2hPV0NadqgNtsbHWwc7L5k711gaFqi9d9dHnxd368gck6OpY4UdUEZnHoRHA9VMIzPWU1UaMAMUm8SIm5WME5Omg4RuJ3Zx==/kisspng-car-rental-rhodes-vehicle-cars-typesetting-5a992e39c9fae4.6422540915199882818273.png" alt="" class="container justify-content-center d-flex">
{% endblock %}

config/vehiculo/templates/listar.html
{% extends "base.html" %}

{% block title %}

    <div class="container">
        <h2 class="mt-3">Listado de vehículos</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Marca</th>
                    <th>Modelo</th>
                    <th>Serial Carrocería</th>
                    <th>Serial Motor</th>
                    <th>Categoría</th>
                    <th>Precio</th>
                    <th>Condición de precio</th>
                </tr>
            </thead>
            <tbody>
                {% for vehiculo in vehiculos %}
                    <tr>
                        <td>{{ vehiculo.marca }}</td>
                        <td>{{ vehiculo.modelo }}</td>
                        <td>{{ vehiculo.serial_carroceria }}</td>
                        <td>{{ vehiculo.serial_motor }}</td>
                        <td>{{ vehiculo.get_categoria_display|upper }}</td>
                        <td>${{ vehiculo.precio }}</td>
                        <td>{{ vehiculo.condicion_precio }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}


config/vehiculo/templates/login.html
{% extends "base.html" %}

{% block content %}
    <div class="container d-flex justify-content-center align-items-center flex-column">
        <h2 class="pt-4 pb-3">Iniciar sesión</h2>
        <div class="card col-4">
            <form class="py-4 px-4" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="text-center mt-3">
                    <button class="btn btn-primary" type="submit">Iniciar sesión</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}